Script started on Tue May  3 03:11:20 2022
[?1034hsh-4.2# ls
Makefile  Project4Output.script  backupFunctions  cpmfsys.c  cpmfsys.h	diskSimulator.c  diskSimulator.h  fsysdriver.c	image1.img  submissionfiles
sh-4.2# make
gcc -c diskSimulator.c
gcc -g -c cpmfsys.c  
gcc -c fsysdriver.c 
gcc -g -o cpmRun diskSimulator.o cpmfsys.o fsysdriver.o 
sh-4.2# ls
Makefile  Project4Output.script  backupFunctions  cpmRun  cpmfsys.c  cpmfsys.h	cpmfsys.o  diskSimulator.c  diskSimulator.h  diskSimulator.o  fsysdriver.c  fsysdriver.o  image1.img  submissionfiles
sh-4.2# ./cpmRun

DIRECTORY LISTING
mytestf1.txt 15874
holefile.txt 1152
shortf.ps  1032
mytestf.    1026

FREE BLOCK LIST: (* Means in-use)
   0:  * . * . * . * . * . * . * . * .
  10:  * . . . . . . . . . . . . . . .
  20:  * . . . * . . . . . . . . . . .
  30:  * * . . . . . . . . . . . . . .
  40:  . . . . . . . . . . . . . . . .
  50:  . . . . . . . . . . . . . . . .
  60:  . . . . . . . . . . . . . . . .
  70:  . . . . . . . . . . . . . . . .
  80:  . . . . . . . . . . . . . . . .
  90:  . . . . . . . . . . . . . . . .
  a0:  * . . . * . . . . . . . . . . .
  b0:  . . . . . . . . . . . . . . . .
  c0:  . . . . . . . . . . . . . . . .
  d0:  . . . . . . . . . . . . . . . .
  e0:  . . . . . . . . . . . . . . . .
  f0:  . * . * . * . * . * . * . * . *


DIRECTORY LISTING
mytestf1.txt 15874
holefile.txt 1152
mytestf.    1026
cpmRename return code = 0,

DIRECTORY LISTING
mytest2.tx 15874
holefile.txt 1152
mytestv2.x 1026

FREE BLOCK LIST: (* Means in-use)
   0:  * . * . * . * . * . * . * . * .
  10:  * . . . . . . . . . . . . . . .
  20:  * . . . * . . . . . . . . . . .
  30:  . . . . . . . . . . . . . . . .
  40:  . . . . . . . . . . . . . . . .
  50:  . . . . . . . . . . . . . . . .
  60:  . . . . . . . . . . . . . . . .
  70:  . . . . . . . . . . . . . . . .
  80:  . . . . . . . . . . . . . . . .
  90:  . . . . . . . . . . . . . . . .
  a0:  * . . . * . . . . . . . . . . .
  b0:  . . . . . . . . . . . . . . . .
  c0:  . . . . . . . . . . . . . . . .
  d0:  . . . . . . . . . . . . . . . .
  e0:  . . . . . . . . . . . . . . . .
  f0:  . * . * . * . * . * . * . * . *

sh-4.2# exit
exit

Script done on Tue May  3 03:11:43 2022
